# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SALT: ${{ secrets.SALT }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements-dev.txt --upgrade --no-cache
      - name: create db
        run: |
          python api/models.py
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with pytest
        run: |
          python -m pytest

      - name: Coverage
        env:
          CODECOV_TOKEN: 5667318f-99cb-4eff-820f-08f5e7c2473f
        run: |
          codecov
      - name: remove db
        run: |
          rm developers.db
